### ISSUE TITLE
Documentation request: Different antialiasing options shown in RStudio

### ISSUE THREAD

**Issue by steveharoz** [r-lib/ragg#100]
RStudio has an `Antialiasing` option right below the option to pick AGG as the backend. The options are:
* (Default)
* None
* Gray
* Subpixel

I'm struggling to find an explanation of what they mean and if they impact **RAGG** at all. `None` and `Subpixel` make sense. But what's `Gray`? And what's the default? Does RAGG even use those settings?

A sentence or two next to the bottom of https://ragg.r-lib.org/ would be helpful.

**Comment by thomasp85** [comment]
They have no effect on ragg which is always using full AA. The setting only affects cairo devices. Optimally this should be documented in the RStudio settings window and maybe only be shown when cairo devices are selected (cc @kevinushey )

**Comment by kevinushey** [comment]
Thanks; I've filed this over at https://github.com/rstudio/rstudio/issues/10281.
