### ISSUE TITLE
Parameter passing for argument of type changed in GCC 7.1

### ISSUE THREAD

**Issue by Byggvir** [r-lib/ragg#107]
When installing under Debian 10 / 11 I get a lot of messages:

note: parameter passing for argument of type changed in GCC 7.1

Example:

`
/usr/include/c++/10/bits/vector.tcc: In member function ‘void std::vector<_Tp, _Alloc>::_M_realloc_insert(std::vector<_Tp, _Alloc>::iterator, _Args&& ...) [with _Args = {textshaping::Point}; _Tp = textshaping::Point; _Alloc = std::allocator<textshaping::Point>]’:
/usr/include/c++/10/bits/vector.tcc:426:7: note: parameter passing for argument of type ‘std::vector<textshaping::Point>::iterator’ changed in GCC 7.1
  426 |       vector<_Tp, _Alloc>::
      |       ^~~~~~~~~~~~~~~~~~~
`

**Comment by thomasp85** [comment]
this is due to textshaping and ragg being build by different versions of GCC - you can avoid this be rebuilding textshaping
