### ISSUE TITLE
Can't reproduce the examples inn the docs

### ISSUE THREAD

**Issue by BatoolMM** [r-lib/ragg#112]
I'm experimenting with RTL languages in R plots. I tried a few methods, including choosing AGG as the backend in the graphics pane in general options.

I'm failing miserably in reproducing the example you have in the docs.
```r

arabic_text <- "هذا مكتوب باللغة العربية"
hebrew_text <- "זה כתוב בעברית"
sindhi_text <- "هي سنڌيءَ ۾ لکيو ويو آهي"

ggplot() + 
  geom_text(
    aes(x = 0, y = 3:1, label = c(arabic_text, hebrew_text, sindhi_text)), 
    family = "Arial"
  ) + 
  expand_limits(y = c(0, 4))

```
![image](https://user-images.githubusercontent.com/53487593/166158428-e822416e-2ee9-4b45-beb3-8de8fe2e0249.png)

```r
> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggrepel_0.9.1       rnaturalearth_0.1.0 ggplot2_3.3.5
```

Sorry but I was wondering if you can suggest a reason why this would behave differently in my local machine?

**Comment by thomasp85** [comment]
Can you provide the versions of systemfonts, textshaping, and ragg on your system?
