### ISSUE TITLE
ggplot2 font changes when deployed and rendered with ragg

### ISSUE THREAD

**Issue by ndiepschroeder** [r-lib/ragg#124]
When ragg is specified as the graphics device in my app via `options(shiny.useragg = TRUE)` the font changes when deployed (via shinyapps.io) versus when seen locally. Disabling ragg returns the font to the same that is used when rendering locally. 
Rendered with ragg on shinyapps.io:
![with_ragg](https://user-images.githubusercontent.com/82720278/216056764-5a0a4b2a-d0a0-4f40-9a9d-657836e92f3f.png)
Rendered without ragg or local:
![without_ragg](https://user-images.githubusercontent.com/82720278/216056772-95d1cbfa-2d53-4298-9676-fdd5bd361c1c.png)

Here is the code for the plot:

```
ggplot(data = df_Zins, aes(x = Jahre, y = Aktueller_Kredit, color = Szenario)) + 
        geom_path() +
        geom_vline(xintercept = Zinsbindung, linetype = 2, color = "darkred", size = 2) +
        theme_minimal() +
        scale_y_continuous(labels = Kommaformatieren, limits = c(0, Anfangs_Kredit + 100000)) +
        labs(
          x = "Jahre nach Kreditabschluss",
          y = "Restschuld"
        ) +
        theme(text = element_text(size = 20),
              legend.position = "bottom",
              plot.title = element_text(hjust = 0.5))
```

**Comment by thomasp85** [comment]
Ragg uses the default font defined by the OS if none is specified. On windows and Mac this is fairly well established, but on linux systems it depend on the content of the systems font-config file... In general you shouldn't rely on non-specified fonts when rendering between systems
