### ISSUE TITLE
white spaces in axis title of exported png

### ISSUE THREAD

**Issue by AlvaroMCMC** [r-lib/ragg#135]
I recently moved to `ragg::agg_png()` because `ggsave()` was not exporting the right family font.

I exported an image to a png file using this code:

```
        ragg::agg_png(
          filename = "image.png",
          width = 15,
          height = 10,
          units = "cm",
          res = 300,
          scaling = 1,
          bg = "white"
        )

        plot(grafico)
        
        dev.off()
```

The left-axis title has more white spaces than needed and it should be "Riqueza de especies".

![image](https://github.com/r-lib/ragg/assets/21317475/aea757cb-913d-4fbf-b224-9f3e04dd0518)

**Comment by thomasp85** [comment]
Can you provide a reprex that creates the issue so I might look into the issue?
