### ISSUE TITLE
Can not install agg_basics.h: No such file or directory

### ISSUE THREAD

**Issue by pati-ni** [r-lib/ragg#139]
In R 4.3 I get the following error when I try to install from CRAN
```
In file included from capture_dev.cpp:1:
ragg.h:13:10: fatal error: agg_basics.h: No such file or directory
   13 | #include "agg_basics.h"
      |          ^~~~~~~~~~~~~~
```

Any idea where this error come from?

**Comment by kylebaron** [comment]
I had the same issue with R 4.3.1 on macos. 

Should be able to find the header file: 
https://github.com/r-lib/ragg/blob/main/src/Makevars.in#L1

But not finding it. I found that removing (renaming) my  `~/.R/Makevars` will get `-I./agg/include` into the mix and the header file will be found. Not sure why my `Makevars` file is overriding the file provided by `ragg`.

**Comment by pati-ni** [comment]
Removing PKG* does the trick
https://github.com/RcppCore/RcppEigen/issues/128
