### ISSUE TITLE
`dev.capabilities("glyphs")` is `NA` instead of `TRUE`

### ISSUE THREAD

**Issue by trevorld** [r-lib/ragg#161]
* It looks like in #159 you updated the `dev.capabilities()` output to report most of the new capabilities.
* However it appears you may have overlooked updating the "glyphs" entry which currently reports `NA`:

```r
ragg::agg_png()
dev.capabilities("glyphs")
invisible(dev.off())
```
```r
$glyphs
[1] NA
```

In contrast the Cairo device reports `TRUE`:

```r
png(type="cairo")
dev.capabilities("glyphs")
invisible(dev.off())
```
```r
$glyphs
[1] TRUE
```

**Comment by thomasp85** [comment]
Thank you for the quick discovery
