### ISSUE TITLE
support for ggblend (multiply, lighten, darken, etc.)

### ISSUE THREAD

**Issue by markjrieke** [r-lib/ragg#163]
blending operations in [ggblend](https://mjskay.github.io/ggblend/index.html) don't appear to be supported by the ragg graphics device. Other devices (e.g., cairo png) work as expected, but using ragg crashes RStudio. Not sure if this is addressable through the ragg package or if it's something more primitive to the OS (macOS in my case).

**Comment by thomasp85** [comment]
This _should_ be fixed in the latest version - can you please test with that

**Comment by markjrieke** [comment]
yes --- works as expected, thank you!!
