### ISSUE TITLE
ggplot theme font not getting mapped properly

### ISSUE THREAD

**Issue by RoyalTS** [r-lib/ragg#168]
I'm not sure if this is a ragg bug, a systemfonts bug, or even whether it is a bug at all or just unexpected behavior. Here goes:

I've been using [hrbrthemes](https://github.com/hrbrmstr/hrbrthemes) forever, always without issue. `theme_ipsum_ps()` from that package ([docs](https://www.rdocumentation.org/packages/hrbrthemes/versions/0.8.7/topics/theme_ipsum_ps)) uses IBM Plex Sans as its font, and using the default Rstudio device the code

```r
mtcars |> 
  ggplot(aes(mpg, wt)) +
  geom_point() +
  hrbrthemes::theme_ipsum_ps() +
  labs(title='This is a title')
```

produces this plot:

<img width="664" alt="Screenshot 2024-06-09 at 19 36 19" src="https://github.com/r-lib/ragg/assets/702580/f5cba82f-293e-440e-9c17-782df6f23241">

All as it should be. If I switch to the AGG device, however, the font no longer seems to be getting rendered correctly:

<img width="653" alt="Screenshot 2024-06-09 at 19 36 39" src="https://github.com/r-lib/ragg/assets/702580/5f543f07-5791-495d-aad9-18af32fce2e8">

This despite the relevant section of `systemfonts::system_fonts()` looking – at least to me – relatively innocuous:

<img width="1028" alt="Screenshot 2024-06-09 at 19 39 15" src="https://github.com/r-lib/ragg/assets/702580/b2019b83-866d-487d-972a-4e45e319e685">

[Possibly related?](https://stackoverflow.com/questions/78391893/why-can-i-not-use-a-system-font-that-is-recognized-by-ggplot2-in-ggiraph)

**Comment by thomasp85** [comment]
The root issue is that systemfonts matches based on the family name, not the post script name. I'll look into if this is possible to add, but I'm not sure if this is doable on all systems

**Comment by thomasp85** [comment]
try with dev systemfonts. I just pushed a potential fix

**Comment by RoyalTS** [comment]
Problem solved, it seems like. Thank you much!
