### ISSUE TITLE
Package should include tests

### ISSUE THREAD

**Issue by jimhester** [r-lib/ragg#22]
A number of issues #21, #20, #19, #18 surfaced when building the vignettes and would probably have come to light sooner if the package had tests as well. Even if the output is difficult to test against a reference just having tests that exercise the code and verify the outputs are approximately the expected size would be useful.

**Comment by thomasp85** [comment]
None of these issues crop up on the linux systems available for CI, so I'm unsure if tests would have caught them (I'm not against having tests though)
