### ISSUE TITLE
Information on cross-platform output

### ISSUE THREAD

**Issue by wch** [r-lib/ragg#28]
It would be helpful if ragg had documentation on what's needed for pixel-perfect image output across platforms. This would help for graphical testing that can run on different platforms.  Does it simply require that the same fonts are installed everywhere? I suppose they would somehow also need to be set as the default fonts that R would select.

**Comment by thomasp85** [comment]
Yeah, the only thing between platforms are the fonts. If the same font is available and chosen it should be identical across platforms. For testing I’d maybe just use graphics not containing any fonts?

If you go with defaults then the chosen fonts will differ across systems as it chooses one that is sure to exist. The next version of systemfonts allow more control over how fonts are chose

**Comment by thomasp85** [comment]
Do you need any additional info on this?

**Comment by wch** [comment]
That's good, thanks.
