### ISSUE TITLE
Add in knitr support

### ISSUE THREAD

**Issue by csgillespie** [r-lib/ragg#29]
This issue https://github.com/r-lib/ragg/issues/17 asked about knitr hooks for ragg. Having the following header:

```{r setup, include=FALSE}
ragg_png = function(..., dpi = 192) ragg::agg_png(..., res = dpi, units = 'in')
knitr::opts_chunk$set(dev = "ragg_png", fig.ext = "png")
```
makes the magic work.

- Is worth creating knitr_ragg functions inside __ragg__?
- If not, probably worth adding this to the README (or some other doc)
- I suppose it might be worth adding ragg to knitr, but this is up to @yihui

Happy to make PRs for points 1 & 2 above

**Comment by yutannihilation** [comment]
Maybe did you mention a wrong person...?

**Comment by csgillespie** [comment]
@yutannihilation Sorry. Autocomplete!
