### ISSUE TITLE
Incorrect shading / colors 

### ISSUE THREAD

**Issue by jeroen** [r-lib/ragg#44]
A user reported that the colors and shading in ragg is off. Here is a minimal example:

```r
library(tidyverse)
library(ragg)

# generate data
group.a <- tibble(values = rnorm(n = 1000, mean = 0, sd = .3),
                  group = "group.a")
group.b <- tibble(values = rnorm(n = 1000, mean = 0, sd = .2),
                  group = "group.b")
group.c <- tibble(values = rnorm(n = 1000, mean = 0, sd = .1),
                  group = "group.c")
combined <- full_join(group.a, group.b)
combined = full_join(combined, group.c)

makeplot <- function(){
  ggplot() +
    scale_x_continuous(limits = c(-1, 1), breaks = c(-1, -.5, 0, .5 , 1)) +
    stat_density(data = combined, aes(x = values, y = factor(group), fill = group, alpha =  stat(density)), geom = "raster", position = "identity") +
    scale_fill_manual(values = c("#BF1E2E" , "#E6C949" , "#2AB9C1")) +
    scale_alpha_continuous(range = c(0.005, 1)) +
    geom_point(data = combined, aes(x = 0, y = group), size = 5, shape = 21, colour = "black", fill = "grey 95")
}


png(filename = "cairo.png", width = 1080, height = 720, res = 144)
makeplot()
dev.off()

agg_png(filename = "ragg.png", width = 1080, height = 720, res = 144)
makeplot()
dev.off()
```

## Base / Cairo

![cairo](https://user-images.githubusercontent.com/216319/83121240-581b9380-a0d2-11ea-92e8-d17c60d3faef.png)

## Ragg

<img width="540" alt="ragg" src="https://user-images.githubusercontent.com/216319/83121251-5c47b100-a0d2-11ea-9aba-1a7384243487.png">

**Comment by thomasp85** [comment]
Is this with the latest release? There were some fixes to premultiplication of input raster in that which looks like it could be the root cause of this...

**Comment by jeroen** [comment]
Yes with the latest release.

**Comment by thomasp85** [comment]
Yeah, I can reproduce. Something funky is going on when the raster is converted to the AGG colour space

**Comment by jeroen** [comment]
Maybe alpha channel?

**Comment by thomasp85** [comment]
I'm almost certain that the premultiplication is not getting performed correctly, so the blending gets messed up

**Comment by thomasp85** [comment]
*phew* 😅 that was thankfully just a 12-character fix (after some hours of source code reading)
