### ISSUE TITLE
particular detection of ggsave

### ISSUE THREAD

**Issue by vandenman** [r-lib/ragg#45]
Hi, just a quick question, feel free to redirect me if there is a better place for that. I noticed this pattern:

```r
if (deparse(sys.call(), nlines = 1, width.cutoff = 500) == 'dev(filename = filename, width = dim[1], height = dim[2], ...)') {
  units <- 'in'
}
```
This essentially checks if somebody does this right?
```r
ggplot2::ggsave(
  ...,
  device = ragg::agg_png,
  ...
)
```
so for `ggsave`, the unit changes to inches rather than anything else. This deviates from the behavior of `ggplot2::ggsave(device = grDevices::png)`. Here `ggsave` recognizes a function, proceeds to do nothing, and saving is done using pixels (unlike when `device = "png"`).

A workaround is this:
```r
ggplot2::ggsave(
  ...,
  device = function(...) ragg::agg_png(...),
  ...
)
```
and then saving is still done using pixels.

My question is, why do you change the units to inches? ggsave also supports `cm` and `mm` (as does `ragg`) so those cannot be used anymore. I'm just curious about the idea behind this design choice, as this may impact how I can use `ragg` (e.g., probably without using `ggsave`).

For what it's worth, below an example that crashes `ggsave`  but not `ragg` as a consequence of this (which lead me to creating this issue):
```r
library(ragg)
library(ggplot2)
g <- qplot(rnorm(10), rnorm(10))
f <- tempfile()

# works
agg_png(filename = f, width = 1500, height = 1000, bg = "transparent", res = 225)
print(g)
dev.off()

# Error in dev(filename = filename, width = dim[1], height = dim[2], ...) : 
#   C++ exception: std::bad_alloc
ggsave(filename = f, width = 1500, height = 1000, device = agg_png, bg = "transparent", res = 225, limitsize = FALSE)

# actual call made by ggsave
# agg_png(filename = f, width = 1500, height = 1000, units = "in", bg = "transparent", res = 225)
```

**Comment by thomasp85** [comment]
This is unintended. That check is related to knitr, not ggsave and I didn't expect this cross-effect (I never use ggsave myself)... I'll look into a better approach
