### ISSUE TITLE
Can't call agg_png inside of a function

### ISSUE THREAD

**Issue by schnee** [r-lib/ragg#54]
See the code below; when I put agg_png inside of a function, if fails to render the plot. I'm guessing this has less to do with ragg and more with my understanding of functions or devices or....

(if the plot is `plot(sin, -pi, 2*pi)` instead of a ggplot, then it works)

```library(ggplot2)
library(ragg)

# this works
file <- "tempfile.png"
agg_png(file)
ggplot(mtcars, aes(x=hp, y=cyl)) + geom_point()
dev.off()


# embedding inside a function
plot_it <- function() {
  file <- "tempfile-func.png"
  agg_png(file)
  ggplot(mtcars, aes(x=hp, y=cyl)) + geom_point()
  dev.off()
}

# the plot is created, but it is empty
plot_it()
```

**Comment by thomasp85** [comment]
You need to print the ggplot2 for it to be rendered.
