### ISSUE TITLE
Is platform-independent text a design goal?

### ISSUE THREAD

**Issue by clauswilke** [r-lib/ragg#55]
Just wondering whether you're planning to support pixel-perfect identical output across platforms in conjunction with the new textshaping package. I was hoping to build a visual difference tool to check output from my html rendering library, but outputs were different across OS X, Windows, and Linux. (I made sure to use the same fonts.) As far as I can tell, systemfonts and textshaping use whichever versions of harfbuzz and freetype2 are installed on the system, which will lead to version-dependent output just like it did with an early version of vdiffr.

Maybe this should be filed with systemfonts or textshaping or both? Related: Issue #28.

**Comment by thomasp85** [comment]
No, this is not a planned feature in any way. The bundling of fixed HarfBuzz and freetype versions for bidder has been a major PITA and I do not want to inherit that

**Comment by clauswilke** [comment]
Got it, no problem.

You may want to consider removing or qualifying this statement in the README, though:
https://github.com/r-lib/ragg/blob/a0b009aad3ace8b7af509474351f26b42cf939e1/README.Rmd#L51-L52
