### ISSUE TITLE
Arial Narrow Font

### ISSUE THREAD

**Issue by csgillespie** [r-lib/ragg#64]
I'm using the following code

```
ggplot(data = data.frame(x = 1:10, y = 1:10)) + 
  geom_point(aes(x, y)) + 
  geom_label(x = 2.5, y = 5,
             label = "This is italic text\n in Arial Narrow",
             family = "Arial Narrow",
             size = 6, label.size = 0)
```
This is the output from a stand png device (it's similar when using Cairo)

![knitr-plot1-1](https://user-images.githubusercontent.com/1267747/101146056-77abef80-3612-11eb-973c-5b1a87a51527.png)

Using ragg I get

![ragg](https://user-images.githubusercontent.com/1267747/101146077-7f6b9400-3612-11eb-8c46-52b970e89767.png)

Two points.

1. The text seems to have a different weight
2. The text in ragg isn't quite Arial Narrow (from my googling). Look the number `5` in particular.

BTW, I know little about fonts

---
```
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] ggplot2_3.3.2
```
Ragg version 0.4.0

**Comment by thomasp85** [comment]
Well, your code would only plot the label text in arial narrow, so it makes sense that the "5" isn't in that font. As for weight, ragg adds a gamma correction to the font when rendering it which gives it a slightly lighter feel (but is correct)

I don't know which font Cairo picks up as default on ubuntu - I thought it would use the same as systemfonts but it is obviously different. ragg uses the system default sans font which I think is the correct approach

**Comment by csgillespie** [comment]
>Well, your code would only plot the label text in arial narrow, so it makes sense that the "5" isn't in that font.
Doh! Sorry
