### ISSUE TITLE
Update documentation for agg_png with ggsave

### ISSUE THREAD

**Issue by jjcrumpler3** [r-lib/ragg#66]
First time I've reported an issue, so please bare with me if I leave anything out.  The protocol for saving a plot with ggsave with device = agg_png seems to have changed, but not clearly communicated within documentation.  

previous example may be something like

`ggsave("mtcars.png", device = agg_png, res = 400)`

However, the working method now is 

`ggsave("mtcars.png", device = agg_png(res = 400))`

I like the change, but it does not seem to be documented anywhere, at least nowhere that I noticed.

**Comment by thomasp85** [comment]
This is not correct. The right way to use ragg with `ggsave()` is the first mentioned approach... There is, however, some unfortunate interaction between the `res` argument in `ragg_png()` and the `dpi` argument in `ggsave()`
