### ISSUE TITLE
New format of calls to `agg_png` in `ggsave` break scaling function:

### ISSUE THREAD

**Issue by andrewbaxter439** [r-lib/ragg#69]
Related to #66 - the updated format for calls of `agg_png` in `ggsave` breaks the `ggsave` code in @thomasp85's [plot scaling walkthrough](https://www.tidyverse.org/blog/2020/08/taking-control-of-plot-scaling/).

These commands produce the same size/resolution image:
``` r
library(ggplot2)
library(ragg)

p <- ggplot(iris, aes(Sepal.Length, Sepal.Width, col = Species)) + geom_point()

ggsave("test1.png",
       p,
       device = agg_png( 
       width = 10,
       height = 5, 
       units = "cm",
       scaling = 1,
       res = 200))
#> Saving 3.94 x 1.96 in image

ggsave("test2.png",
       p,
       device = agg_png( 
       width = 40,
       height = 20, 
       units = "cm",
       scaling = 4,
       res = 200))
#> Saving 3.94 x 1.97 in image
```

Whereas these work as expected (with same arguments outside of `ggsave`:
``` r
library(ggplot2)
library(ragg)

p <- ggplot(iris, aes(Sepal.Length, Sepal.Width, col = Species)) + geom_point()


agg_png("test1.png", 
        width = 10,
        height = 5, 
        units = "cm",
        res = 200)
print(p)
dev.off()

agg_png("test2.png",
        width = 40, 
        height = 20,
        units = "cm", 
        res = 200,
        scaling = 4)
print(p)
dev.off()
```

<sup>Created on 2021-01-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
where have you seen this "updated format" being advertised?

**Comment by andrewbaxter439** [comment]
ah good question, was just going off other issue. Putting the arguments to pass to `agg_png` outside of the brackets don't seem to work as expected:
```r
ggsave("test.png",
       p,
       device = agg_png, 
       width = 10,
       height = 5,
       units = "cm",
       res = 100)
```
... produces an image 3px*1px. Putting these parts in the brackets does produce the image the correct size, but `scaling` argument within `agg_png` brackets within `ggsave` doesn't work as expected. Apologies if I'm misunderstanding this (and other issue is unrelated).

**Comment by thomasp85** [comment]
I'm not sure if `ggsave()` handles ragg correctly to be honest, but that is an issue for `ggplot2`, not ragg 🙂

**Comment by andrewbaxter439** [comment]
Thanks @thomasp85 - can look more into it and open a `ggplot2` issue if there's still a problem. Was excited to find a way of mastering scaling plots but still trying to figure out some parts of it :)
