### ISSUE TITLE
ragg and fonts

### ISSUE THREAD

**Issue by jonathon-love** [r-lib/ragg#70]
hi,

i assume this is a font issue, but i'm finding under macOS that `ragg` does not display hebrew, japanese, characters, where as the default XQuartz renderer does. i.e.

```
ggplot2::ggplot() + ggplot2::xlab('קבוצה')
```

produces the squares in each character's place.

i don't think i have this problem on linux. i have `systemfonts` installed.

is there a way for this to work?

(ragg is really fabulous btw. saves us a lot of heart-ache with environments that don't support X, etc.)

with thanks

**Comment by thomasp85** [comment]
You'll be pleased with the next release (due within the week, CRAN permitting)

This has been the focus of many months of work :-)
