### ISSUE TITLE
Fonts appear lighter with ragg (linux).

### ISSUE THREAD

**Issue by JohannesNE** [r-lib/ragg#75]
According to the answer to https://github.com/r-lib/ragg/issues/64, fonts appear lighter with ragg due to gamma correction, is there any way to disable/tune this?  

In the example below, I think the default (cairo?) version has a nicer header, while the ragg version has a more readable geom_text output.

Generally, the appearance of plots after changing the default graphics device in RStudio to AGG is similar to the default appearance on windows. 

```
library(tidyverse)

p <- ggplot() + 
  geom_text(
    aes(x = 0, y = 0, 
        label = paste(names(R.Version()), 
                      R.Version(), 
                      sep = ": ", collapse = "\n")
        )) +
  labs(title = "Header", subtitle = "Subtitle", 
       x = "x-axis label", y = "y-axis label")

ragg::agg_png("ragg_plot.png", width = 400, height = 400)
p
dev.off()

png("default_plot.png", width = 400, height = 400)
p
dev.off()
```

With `ragg::agg_png()`
![ragg_plot](https://user-images.githubusercontent.com/11048760/108176502-64cd9500-7102-11eb-9a28-2d7c1b3b7a06.png)

With `png()`
![default_plot](https://user-images.githubusercontent.com/11048760/108176516-6ac37600-7102-11eb-9a36-d44ccbc29f61.png)

**Comment by thomasp85** [comment]
The latest ragg release have tweaked this a bit so the fonts are slightly heavier than before. It is not really something that will be exposed to the user
