### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [r-lib/ragg#8]
Would you like to wrap any pointer data members with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

Update candidates:
- [AggDevice](https://github.com/thomasp85/ragg/blob/9ce33a0e5a3e059a184aaafdb3e2e61aef6c917e/src/AggDevice.h#L149)
- [AGGView](https://github.com/thomasp85/ragg/blob/c72cf825c2b3ad0188be7e6264ccfa90e34ba553/src/agg/src/platform/BeOS/agg_platform_support.cpp#L142)
- [font_engine_freetype_base](https://github.com/thomasp85/ragg/blob/ee4e32ebd4604781ad7855fab3e75044b6d3950d/src/agg/src/agg_font_freetype.cpp#L514)

**Comment by thomasp85** [comment]
I'll definitely do that for the classes I provide myself... AGGView is not really used in ragg and will probably be removed in a pruning of the AGG source. I'll have to think more careful about the font_engine but I might make unrelated changes to that as well so I might incorporate this
