### ISSUE TITLE
Catch invalid device resolution or units (segmentation fault)

### ISSUE THREAD

**Issue by hsbadr** [r-lib/ragg#82]
If the user passes large resolution or inappropriate units, some devices are unable to start or cause a segmentation fault.

Examples:

```r
> ragg::agg_png(res = 100, units = "in")
Error in ragg::agg_png(res = 100, units = "in") :
  C++ exception: std::bad_alloc
```

```r
> ragg::agg_png(res = 300, units = "in")

 *** caught segfault ***
address 0x14699b355000, cause 'invalid permissions'

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:
```

This is caught by `grDevices` as follows:

```r
> grDevices::png(res = 300, units = "in")
Error in grDevices::png(res = 300, units = "in") :
  unable to start device 'png'
In addition: Warning message:
In grDevices::png(res = 300, units = "in") :
  cairo error 'invalid value (typically too big) for the size of the input (surface, pattern, etc.)'
```

**Comment by thomasp85** [comment]
This is probably a good idea, thanks!

**Comment by hsbadr** [comment]
> This will now give:

Thanks @thomasp85 !

> The second example is harder to handle correctly

I see.

> I've decided to set a maximum dimension which is controllable through an option

Thanks! Was going to suggest this:
Is there a way to estimate the image size and add a warning after checking the arguments? Even if it causes a segfault, a warning will make it easier to debug (e.g., with `options(warn = 2)`).

**Comment by thomasp85** [comment]
Are you suggesting anything in addition?

**Comment by hsbadr** [comment]
> Are you suggesting anything in addition?

I'll get back to you after debugging the current version of `ragg` on my system. I'll open a new issue, if I found the culprit with reproducible examples on other platforms.

**Comment by thomasp85** [comment]
Are we discussing the issue raised in the ggplot2 repo here? In the above I was more alluring to your comment about estimating image size and whether the current setup addresses that

**Comment by hsbadr** [comment]
Yes, what I was suggesting is to estimate the required memory size and return a warning if it exceeds a limit; though, the new `ragg.max_dim` option may do it.

**Comment by hsbadr** [comment]
The good thing about memory check is that you may use the available/physical memory as a dynamic limit.

**Comment by thomasp85** [comment]
The default max is set so high that if you ever reach it you are in "here-be-dragons" territory and on your own... 

I don't know of any way to reliably estimate memory available to a process so I'd rather not go that route

**Comment by hsbadr** [comment]
> I don't know of any way to reliably estimate memory available to a process so I'd rather not go that route

The estimated memory size depends on the data type and dimensions. It's an easy estimate (e.g., multiply the type size, e.g. 8 bytes, by the total number of pixels) and can be compared to a fraction of the available memory (e.g., a memory limit of 50% or so).

**Comment by hsbadr** [comment]
There's also a `memuse` package, but I haven't tested/used it.
