### ISSUE TITLE
Can't install on linux machine with R 4.0.0 

### ISSUE THREAD

**Issue by cscheeder** [r-lib/ragg#84]
# Can't install via devtools::install_github('r-lib/ragg') or install.packages('ragg')

## Error: 
agg/src/agg_font_freetype.cpp: In member function ‘bool agg::font_engine_freetype_base::load_font(const char*, unsigned int, agg::glyph_rendering, const char*, long int)’:
agg/src/agg_font_freetype.cpp:718:44: error: ‘FT_HAS_COLOR’ was not declared in this scope
                 if (FT_HAS_COLOR(m_cur_face))
                                            ^
agg/src/agg_font_freetype.cpp: In member function ‘bool agg::font_engine_freetype_base::prepare_glyph(unsigned int)’:
agg/src/agg_font_freetype.cpp:981:84: error: ‘FT_LOAD_COLOR’ was not declared in this scope
                                      m_glyph_rendering == glyph_ren_native_color ? FT_LOAD_COLOR : (m_hinting ? FT_LOAD_DEFAULT : FT_LOAD_NO_HINTING));
                                                                                    ^
make: *** [agg/src/agg_font_freetype.o] Error 1
ERROR: compilation failed for package ‘ragg’
* removing ‘/home/R/x86_64-pc-linux-gnu-library/4.0/ragg’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpuioOTe/file5bb41b11b44b/ragg_1.1.3.9000.tar.gz’ had non-zero exit status

## from SessionInfo()
version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Thanks!

**Comment by thomasp85** [comment]
Try updating freetype

**Comment by cscheeder** [comment]
solved, thanks!

**Comment by fabriciofialho** [comment]
I am getting this same `agg_font_freetype.o` error message, now in 2024, on R 4.4 running on Arch/Endeavour: 

agg/src/agg_font_freetype.cpp:182:35: error: invalid conversion from ‘unsigned char*’ to ‘char*’ [-fpermissive]
  182 |             tags  = outline.tags  + first;
      |                     ~~~~~~~~~~~~~~^~~~~~~
      |                                   |
      |                                   unsigned char*
make: *** [/usr/lib64/R/etc/Makeconf:204: agg/src/agg_font_freetype.o] Error 1
ERROR: compilation failed for package ‘ragg’
* removing ‘/home/machiavelli/R/x86_64-pc-linux-gnu-library/4.4/ragg’




I already updated freetype running (with success)  `sudo pacman -S freetype2` on terminal. 


> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: EndeavourOS

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas.so.0.3;  LAPACK version 3.12.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/London
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.4.1 tools_4.4.1

**Comment by ablechow29** [comment]
I ran into the exact shame issue. However `sudo pacman -S freetype2` did not resolve the issue.

```
agg/src/agg_font_freetype.cpp:1071:48:   required from here
 1071 |                         if(decompose_ft_outline(m_cur_face->glyph->outline,
      |                            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1072 |                                                 m_flip_y,
      |                                                 ~~~~~~~~~
 1073 |                                                 m_affine,
      |                                                 ~~~~~~~~~
 1074 |                                                 m_path32))
      |                                                 ~~~~~~~~~
agg/src/agg_font_freetype.cpp:182:35: error: invalid conversion from ‘unsigned char*’ to ‘char*’ [-fpermissive]
  182 |             tags  = outline.tags  + first;
      |                     ~~~~~~~~~~~~~~^~~~~~~
      |                                   |
      |                                   unsigned char*
agg/src/agg_font_freetype.cpp: In instantiation of ‘bool agg::decompose_ft_outline(const FT_Outline&, bool, const trans_affine&, PathStorage&) [with PathStorage = path_
storage_integer<short int, 6>; FT_Outline = FT_Outline_]’:
agg/src/agg_font_freetype.cpp:1092:48:   required from here
 1092 |                         if(decompose_ft_outline(m_cur_face->glyph->outline,
      |                            ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1093 |                                                 m_flip_y,
      |                                                 ~~~~~~~~~
 1094 |                                                 m_affine,
      |                                                 ~~~~~~~~~
 1095 |                                                 m_path16))
      |                                                 ~~~~~~~~~
agg/src/agg_font_freetype.cpp:182:35: error: invalid conversion from ‘unsigned char*’ to ‘char*’ [-fpermissive]
  182 |             tags  = outline.tags  + first;
      |                     ~~~~~~~~~~~~~~^~~~~~~
      |                                   |
      |                                   unsigned char*
make: *** [/usr/lib64/R/etc/Makeconf:204: agg/src/agg_font_freetype.o] Error 1
ERROR: compilation failed for package ‘ragg’
* removing ‘/home/able/R/x86_64-pc-linux-gnu-library/4.4/ragg’

The downloaded source packages are in
        ‘/tmp/RtmpawsYDP/downloaded_packages’
Warning message:
In install.packages("ragg", repos = "https://cloud.r-project.org") :
  installation of package ‘ragg’ had non-zero exit status
>
```

**Comment by fabriciofialho** [comment]
Try downloading the most recent tar file from

https://r-lib.r-universe.dev/ragg

and install the package from it.

It worked in my case.
